# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c113176763ee61410e4a03e29668164b196bd006f68dc87a1cd54aee3bbd77b3f001d909488228862a598c3d5a270d0362edcea6c7b3269b8f3bc5dfa3a6b4f

test:
  secret_key_base: ac586963860204da44e14870f62e5c63d386ace1a45ab564fb38191270c2836306113fb84c1bcf228f0be460ad1696b80d568eda36c957b5124e745d73ec6f6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
